export const INTENT_REGISTRY_ADDRESS = process.env.NEXT_PUBLIC_INTENT_REGISTRY_ADDRESS;
export const INTENT_ROUTER_ADDRESS = process.env.NEXT_PUBLIC_INTENT_ROUTER_ADDRESS;
export const XCM_BRIDGE_ADDRESS = process.env.NEXT_PUBLIC_XCM_BRIDGE_ADDRESS;
export const RPC_URL = process.env.NEXT_PUBLIC_RPC_URL;
export const CHAIN_ID = process.env.NEXT_PUBLIC_CHAIN_ID;
